### ISSUE TITLE
请问model.pv 在哪

### ISSUE THREAD

**Issue by zjduck0728** [kadoufall/news-recommender#2]

**Comment by kadoufall** [comment]
执行`TrainVsmModel.java`的`train`方法可以得到

文件在`src/main/java/com/kadoufall/recommender/service/contentBased`目录下

**Comment by wqyan** [comment]
嗯。。谢谢。我已经做出来了。。很感谢


------------------ 原始邮件 ------------------
发件人: "kadoufall"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 晚上11:29
收件人: "kadoufall/news-recommender"<news-recommender@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [kadoufall/news-recommender] 请问model.pv 在哪 (#2)




执行TrainVsmModel.java的train方法可以得到
 
文件在src/main/java/com/kadoufall/recommender/service/contentBased目录下

**Comment by zjduck0728** [comment]
感谢~@kadoufall 
今天测试基于用户的协同过滤推荐服务，dubeg发现浏览器一直卡在
`UserCFRecommenderServiceImpl.java` 的` recommend` 方法的以下行代码
` List<RecommendedItem> recommendedItems = recommender.recommend(userId, this.recommendNum);`
IDE也一直显示**The application is running.** 请问有出现过类似情况吗？求解

**Comment by zjduck0728** [comment]
后面过了10多分钟，才有反应，即产生推荐结果了，但这推荐速度太慢了，用户体验不好，怎样改善呢？

**Comment by wqyan** [comment]
如果真正的推荐系统，可以考虑大数据并行处理，例如spark，hadoop等等。




------------------ 原始邮件 ------------------
发件人: "lingb"<notifications@github.com>;
发送时间: 2019年5月6日(星期一) 下午4:57
收件人: "kadoufall/news-recommender"<news-recommender@noreply.github.com>;
抄送: "严文强"<643320250@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [kadoufall/news-recommender] 请问model.pv 在哪 (#2)




后面过了10多分钟，才有反应，即产生推荐结果了，但这推荐速度太慢了，用户体验不好，怎样改善呢？

**Comment by zjduck0728** [comment]
@wqyan 
嗯我想也是推荐引擎计算拖了时间，请问你是已经使用大数据实现了吗？

**Comment by wqyan** [comment]
暂时还没有实现，我的研究重点不是大数据。以后工作中可能要处理这个大数据问题。




------------------ 原始邮件 ------------------
发件人: "lingb"<notifications@github.com>;
发送时间: 2019年5月6日(星期一) 下午5:11
收件人: "kadoufall/news-recommender"<news-recommender@noreply.github.com>;
抄送: "严文强"<643320250@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [kadoufall/news-recommender] 请问model.pv 在哪 (#2)




@wqyan
 嗯我想也是推荐引擎计算拖了时间，请问你是已经使用大数据实现了吗？

**Comment by zjduck0728** [comment]
> 暂时还没有实现，我的研究重点不是大数据。以后工作中可能要处理这个大数据问题。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "lingb"<notifications@github.com>; 发送时间: 2019年5月6日(星期一) 下午5:11 收件人: "kadoufall/news-recommender"<news-recommender@noreply.github.com>; 抄送: "严文强"<643320250@qq.com>; "Mention"<mention@noreply.github.com>; 主题: Re: [kadoufall/news-recommender] 请问model.pv 在哪 (#2) @wqyan 嗯我想也是推荐引擎计算拖了时间，请问你是已经使用大数据实现了吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

好的，谢谢你蛤~

**Comment by kadoufall** [comment]
@a-yin 
- 这里使用的是`MySQLBooleanPrefJDBCDataModel`，所以跟数据库传输数据的时间也有关系，可以换成`GenericBooleanPrefDataModel`然后结合`FileDataModel`试一下，应该会快很多
```java
DataModel model = new GenericBooleanPrefDataModel(
        GenericBooleanPrefDataModel.toDataMap(
          new FileDataModel(new File("ua.base"))
        )
);
```
- 另外`Mahout`有分布式计算的接口，结合`MapReduce`和`Spark`可以尝试

**Comment by kadoufall** [comment]
> @a-yin
> 
> * 这里使用的是`MySQLBooleanPrefJDBCDataModel`，所以跟数据库传输数据的时间也有关系，可以换成`GenericBooleanPrefDataModel`然后结合`FileDataModel`试一下，应该会快很多
> 
> ```java
> DataModel model = new GenericBooleanPrefDataModel(
>         GenericBooleanPrefDataModel.toDataMap(
>           new FileDataModel(new File("ua.base"))
>         )
> );
> ```
> 
> * 另外`Mahout`有分布式计算的接口，结合`MapReduce`和`Spark`可以尝试

可以用这个文件：`src/main/resources/caixin.base`

**Comment by zjduck0728** [comment]
@kadoufall 

嗯速度上去了，体验也好了

**Comment by cui-wei-li** [comment]
你好，我想问一下这个项目有没有详细点的文档呢？

**Comment by cui-wei-li** [comment]
> @kadoufall
> 
> 嗯速度上去了，体验也好了
你好，我想问一下这个具体用了什么技术来提升速度呢？

**Comment by kadoufall** [comment]
> 你好，我想问一下这个项目有没有详细点的文档呢？

现在没有哈

**Comment by kadoufall** [comment]
> > @kadoufall
> > 嗯速度上去了，体验也好了
> > 你好，我想问一下这个具体用了什么技术来提升速度呢？

这个就是改成内存计算了，所以快了
